/**
 * @file shoes.h
 * @brief C interface for the shoes proxy library (auto-generated by cbindgen).
 *
 * Provides C-compatible functions for embedding the shoes VPN/proxy engine
 * into iOS applications via Swift or Objective-C.
 */

#ifndef SHOES_H
#define SHOES_H

#include <stdbool.h>
#include <stdint.h>

/**
 * Socket protector callback type.
 * Called from Rust to protect sockets from VPN routing.
 * The callback receives a file descriptor and should return true if protected successfully.
 *
 * Like the stopped callback, a call already in flight when `shoes_stop`
 * begins may still complete after `shoes_stop` returns -- the pointer
 * must stay valid until then (a non-capturing function, not a freed
 * trampoline). A protect that runs after the slot is cleared reports
 * success without protecting; the socket it was for belongs to a
 * session that is already gone.
 */
typedef bool (*ProtectSocketCallback)(int fd);

/**
 * Traffic statistics callback type.
 * Called about once a second with cumulative byte counts since `shoes_start`.
 *
 * * `upload_bytes` - total bytes sent from the device to the proxy.
 * * `download_bytes` - total bytes received from the proxy to the device.
 *
 * Invoked from a Rust worker thread, not the caller's thread.
 */
typedef void (*ShoesTrafficCallback)(uint64_t upload_bytes, uint64_t download_bytes);

/**
 * Engine-stopped callback type.
 *
 * Called once, from a shoes worker thread, when the engine stops without
 * `shoes_stop` having been called: a failure, or a task that ended on its
 * own. `reason` is the failure message -- currently always non-NULL: an
 * unrequested clean end carries "service ended without being asked".
 * NULL stays reserved for "no reason", so treat it as such if it ever
 * appears; the pointer is
 * valid for the duration of the call only, and `shoes_get_last_error`
 * returns the same text afterwards. Never called for a stop the host
 * requested and never for a start that failed; a call already in flight
 * when `shoes_stop` begins may still complete after `shoes_stop` returns.
 * `shoes_is_running()` is already false when it runs, and calling
 * `shoes_stop` from inside it is allowed. Do not block in it.
 *
 * Do not call `shoes_start` from inside it: the callback runs on a
 * worker of the dying session's runtime, and a start there is refused
 * with an error (it would otherwise abort the process). Dispatch the
 * reconnect to another thread or queue instead.
 *
 * May be NULL, in which case nothing is called.
 */
typedef void (*ShoesStoppedCallback)(const char *reason);

/**
 * Initialize the shoes library.
 *
 * # Arguments
 * * `log_level` - Log level string: "error", "warn", "info", "debug", "trace"
 *
 * # Returns
 * * 0 on success
 * * -1 on error
 *
 * # Safety
 * `log_level` must be a valid null-terminated C string.
 */
int shoes_init(const char *log_level);

/**
 * Start the shoes VPN service.
 *
 * # Arguments
 * * `config_yaml` - YAML configuration string (must include device_fd in TUN config)
 * * `protect_callback` - Callback function to protect sockets from VPN routing
 * * `traffic_callback` - Callback invoked about once a second with cumulative
 *   upload and download byte counts
 *
 * # The TUN descriptor is borrowed, not transferred
 *
 * The caller opens the device and owns the descriptor for the whole session.
 * shoes reads from `device_fd` until `shoes_stop` returns and never closes
 * it -- not on shutdown, not on error, not at any point in between. There is
 * no flag that changes this: closing a descriptor the host still holds would
 * be the worse failure of the two, since the number is immediately recycled
 * by the next `socket()` or `open()` in the process.
 *
 * So the descriptor must stay open across the whole session, and closing it
 * is the caller's job once `shoes_stop` has returned. Not closing it leaks
 * the descriptor, and where the platform ties the tunnel interface to the
 * descriptor, the tunnel outlives the stop.
 *
 * # Returns
 * * Handle (> 0) on success
 * * -1 on error
 *
 * Installs no stopped callback; use `shoes_start_with_fd` for one.
 *
 * # Safety
 * `config_yaml` must be a valid null-terminated C string.
 */
long shoes_start(const char *config_yaml,
                 ProtectSocketCallback protect_callback,
                 ShoesTrafficCallback traffic_callback);

/**
 * Start the shoes VPN service with the TUN descriptor passed as a parameter.
 *
 * Identical to `shoes_start` in every other respect, including that the
 * descriptor is borrowed and never closed. The difference is where the
 * descriptor comes from: `device_fd` here overrides a `device_fd` the YAML
 * carries and fills one it omits, so a config generated before the
 * descriptor existed -- by the app, for an extension that learns its fd from
 * `packetFlow` -- needs no textual patching before it is handed over. A
 * generator may write `device_fd: 0` as a stand-in or leave the field out.
 *
 * The config must still contain a `tun` section; the parameter names the
 * descriptor for it, it does not create one.
 *
 * # Arguments
 * * `config_yaml` - YAML configuration string
 * * `device_fd` - the TUN descriptor, owned by the caller, open until
 *   `shoes_stop` returns
 * * `protect_callback` - as for `shoes_start`
 * * `traffic_callback` - as for `shoes_start`
 * * `stopped_callback` - see `ShoesStoppedCallback`; may be NULL
 *
 * # Returns
 * * Handle (> 0) on success
 * * -1 on error; `shoes_get_last_error` says why
 *
 * # Safety
 * `config_yaml` must be a valid null-terminated C string.
 */
long shoes_start_with_fd(const char *config_yaml,
                         int device_fd,
                         ProtectSocketCallback protect_callback,
                         ShoesTrafficCallback traffic_callback,
                         ShoesStoppedCallback stopped_callback);

/**
 * Stop the shoes VPN service.
 *
 * Signals shutdown and blocks until the engine has released the TUN
 * descriptor -- milliseconds in practice, bounded at 5 seconds if a task
 * will not wind down. Do not call it from a thread that has a watchdog
 * budget of its own; on Android the ANR budget is about the same 5 seconds.
 *
 * # The descriptor is yours to close, after this returns
 *
 * shoes is still reading `device_fd` until this call returns, so closing it
 * first closes a descriptor the engine holds, and the number is then handed
 * to the next socket the process opens. Closing it afterwards is the
 * caller's job -- shoes never closes it. See `shoes_start`.
 *
 * What that close does is platform-dependent, and on one platform it is not
 * optional:
 *
 * * Android: the app created the descriptor with
 *   `VpnService.Builder.establish()`, and closing it is what takes the TUN
 *   interface down. Skip it and the interface stays up, the system will not
 *   destroy the `VpnService`, and the next start finds one already running.
 *   Note that `ParcelFileDescriptor.detachFd()` moves ownership out of the
 *   wrapper, so `close()` on that wrapper afterwards closes nothing.
 * * iOS: the descriptor was read off `NEPacketTunnelProvider.packetFlow` and
 *   belongs to a live NetworkExtension object, which tears it down with the
 *   extension. An app that did not create it has nothing to close.
 *
 * # Returns
 * * 1 - the engine confirmed the stop; the descriptor is released and
 *   yours to close.
 * * 0 - the wait timed out and the engine may still be reading the
 *   descriptor. Closing it now risks the fd-recycling hazard described
 *   above; prefer leaking it to closing it.
 *
 * Earlier releases returned nothing and every caller had to assume 1.
 * Ignoring the result reproduces exactly that behavior.
 *
 * # Arguments
 * * `handle` - Handle returned by shoes_start (currently unused, we use global state)
 */
int shoes_stop(long _handle);

/**
 * Check if the shoes service is running.
 *
 * # Returns
 * * true if running
 * * false if not running
 */
bool shoes_is_running(void);

/**
 * Get the shoes library version.
 *
 * # Returns
 * A static string containing the version. Do not free this pointer.
 */
const char *shoes_get_version(void);

/**
 * Set the log file path for file-based logging.
 *
 * # Arguments
 * * `path` - Absolute path to the log file
 *
 * # Returns
 * * 0 on success
 * * -1 on error
 *
 * # Safety
 * `path` must be a valid null-terminated C string.
 */
int shoes_set_log_file(const char *path);

/**
 * Change the log level of a running library.
 *
 * `shoes_init` reads the level once and ignores it on every later call, so
 * without this a support workflow of "turn on debug logging and reproduce"
 * means killing the app first. Takes effect immediately, for every subsequent
 * record.
 *
 * Note that release builds are compiled with `release_max_level_info`, so
 * "debug" and "trace" only differ from "info" in a build that keeps them.
 *
 * # Arguments
 * * `log_level` - "error", "warn", "info", "debug", "trace", or "off"
 *
 * # Returns
 * * 0 on success
 * * -1 if the level was not recognised
 *
 * # Safety
 * `log_level` must be a valid null-terminated C string.
 */
int shoes_set_log_level(const char *log_level);

/**
 * Tell the library the device's network changed.
 *
 * Call this from `NWPathMonitor`'s update handler. A UDP tunnel bound to an
 * address that no longer exists does not fail — it goes silent — so without
 * this the only recovery is a full stop and start, which tears down the TUN
 * interface and every connection through it. This rebinds the tunnel's socket
 * in place instead.
 *
 * Safe to call at any time, including when no tunnel is running. It does no
 * I/O on the calling thread.
 *
 * # Returns
 * The number of tunnel endpoints that were told to rebind.
 */
int shoes_network_changed(void);

/**
 * Get the last error message from the shoes service.
 *
 * Returns a null-terminated C string containing the error message,
 * or NULL if no error has occurred. The caller must free the returned
 * string using `shoes_free_string()`.
 *
 * Thread-safe. The returned string is a copy — safe to use after
 * subsequent shoes API calls.
 */
char *shoes_get_last_error(void);

/**
 * Read the runtime counters as a JSON document.
 *
 * Returns a null-terminated UTF-8 string the caller must free with
 * `shoes_free_string()`, or NULL if no document could be produced.
 *
 * NULL is not a statement about the service. A library built without the
 * `control-stats` feature returns NULL always; otherwise NULL means only
 * that the string could not be built, which is not expected to be reachable
 * here but is not worth an abort. **Do not latch the first NULL as "this
 * build has no stats"** -- the Android side of this API shares the contract
 * and can fail that way under JVM memory pressure. Poll again.
 *
 * A non-NULL document is always well formed. Before `shoes_start` every
 * number is zero and `outbounds` is empty; after `shoes_stop` it holds the
 * final figures of the session that just ended, and the next `shoes_start`
 * resets them.
 *
 * Safe to call from any thread, and safe when nothing is running. It does no
 * I/O -- it takes a short read lock on the outbound registry and allocates
 * the string.
 *
 * The document has this shape, and later releases may add keys to it, so a
 * host should ignore keys it does not recognise:
 *
 *   {"upload_bytes":0,"download_bytes":0,"active_connections":0,
 *    "outbounds":[{"name":"Frankfurt","upload_bytes":0,"download_bytes":0,
 *                  "active_connections":0}]}
 *
 * `upload_bytes` and `download_bytes` at the top level are the same two
 * totals `ShoesTrafficCallback` delivers, measured at the TUN edge.
 * `active_connections` at the top level is live TCP connections through the
 * tunnel. Each `outbounds` entry is measured at the proxy instead: its bytes
 * are application payload to and from that server, and its
 * `active_connections` counts streams open to it. The two measurements do
 * not agree to the byte and are not meant to -- see src/control/stats.rs.
 * `outbounds` is sorted by name and lists every outbound in the running
 * config, including ones that have carried nothing yet.
 */
char *shoes_get_stats(void);

/**
 * Free a string returned by `shoes_get_last_error()` or `shoes_get_stats()`.
 *
 * # Safety
 * `ptr` must be a pointer returned by one of those two functions, or NULL,
 * and must not have been freed already.
 */
void shoes_free_string(char *ptr);

#endif  /* SHOES_H */
